bangla_meaning = {
    "abate": "হ্রাস করা",
    "aberrant": "বিপথগামী, অস্বাভাবিক",
    "abet": "অসৎ কাজে সাহায্য করা",
    "abeyance": "সাময়িক সময়ের জন্য় স্থগিত করা",
    "abhor": "ঘৃণাসহকারে পরিহার করা",
    "abide": "মেনে চলা",
    "abject": "শোচনীয়",
    "abjure": "শপথপূর্বক পরিত্যাগ করা",
    "abound": "প্রচুর পরিমানে বিদ্য়মান থাকা",
    "abreast": "পাশাপাশি",
    "abscond": "পলান",
    "abstain": "বিরত থাকা",
    "abstract": "তাত্ত্বিক",
    "accentuate": "উচ্চারণ করা",
    "accessible": "সহজলভ্য, প্রবেশযোগ্য",
    "acclaim": "উচ্চৈঃস্বরে প্রশংসা করা",
    "acolyte": "সহকারী",
    "acquiesce": "নীরবে সম্মতি দেওয়া",
    "acquisitive": "অর্জন করিতে ইচ্ছুক",
    "acrimonious": "উগ্র, বদমেজাজি",
    "acumen": "সূক্ষ্ম বিচারশক্তি",
    "adept": "সুদক্ষ",
    "admonish": "সতর্ক করা",
    "adroit": "দক্ষ, নিপুণ",
    "adulterate": "ভেজালমিশ্রিত",
    "adverse": "প্রতিকূল",
    "advocate": "উকিল",
    "aesthetic": "নান্দনিক",
    "affectation": "ভান",
    "affinity": "ঝোঁক",
    "affront": "অপমান করা",
    "aggrandize": "ক্ষমতা বা সম্পদ বৃদ্ধি করা, অতিরঁজিত করা",
    "agitate": "উত্তেজিত করা",
    "alacrity": "কর্মচাঞ্চল্য, উদ্দীপনা",
    "alienate": "দূরে সরিয়ে দেওয়া, বিচ্ছিন্ন করা",
    "alleviate": "উপশম করা",
    "allusive": "ইঙ্গিতপূর্ণ",
    "aloof": "দূরে দূরে থাকা",
    "altruistic": "পরার্থপর, কল্যাণময়",
    "amalgamate": "জোড়া লাগানো",
    "ambivalent": "পরস্পরবিরোধী",
    "ameliorate": "উন্নয়নসাধন করা",
    "amenable": "নমনীয়, বাধ্য",
    "amend": "সংশোধন করা",
    "amicable": "বন্ধুত্বপূর্ণ",
    "amorphous": "নিরাকার",
    "anachronistic": "সময়ের অসঙ্গতি বা ভুল",
    "analogous": "অনুরূপ",
    "animosity": "শত্রুতা",
    "animus": "শত্রুতা",
    "anoint": "তেল মাখানো",
    "anomalous": "ব্যতিক্রমী, অস্বাভাবিক",
    "antagonize": "শত্রুভাবাপন্ন করে তোলা",
    "antedate": "প্রকৃত সময়ের পূর্ববর্তী তারিখ প্রদান করা",
    "antipathy": "বিদ্বেষ, বিরোধীতা",
    "antithesis": "বৈপরীত্য",
    "apathy": "ঔদাসীন্য",
    "apogee": "সর্বোচ্চ সীমা",
    "apologist": "কৈফিয়তদানকারী",
    "appease": "প্রশমিত করা",
    "apprehension": "আশঙ্কা, উপলদ্ধি করতে পারা, গ্রেপ্তার",
    "approbation": "অনুমোদন",
    "appropriate": "যথাযথ",
    "apropos": "মানানসই",
    "apt": "যথাযথ",
    "arbitrary": "ইচ্ছামত; স্বৈর",
    "arcane": "রহস্যময়",
    "archaic": "প্রাচীন",
    "archetype": "মূল আদর্শ",
    "ardent": "উৎসাহী",
    "arduous": "শ্রমসাধ্য",
    "arresting": "মনোযোগ আকর্ষণকারী, চমকপ্রদ",
    "articulate": "স্পষ্ট করে বলা",
    "artless": "সরল, আলাভোলা",
    "ascertain": "নিশ্চিত করা",
    "ascetic": "সাধু, তপস্বী, যোগী",
    "ascribe": "আরোপ করা",
    "aspersion": "কলঙ্ক",
    "assail": "আক্রমণ করা",
    "assertive": "জিদপূর্ণ, নিশ্চয়কর",
    "assuage": "প্রশমিত করা, হ্রাস করা, কমানো",
    "astringent": "সংকোচক",
    "astute": "বিচক্ষণ",
    "attenuate": "শক্তিহীন করা",
    "audacious": "দুঃসাহসী",
    "augment": "বৃদ্ধি",
    "august": "সম্মান করা, শ্রদ্ধা করা",
    "auspicious": "সুপ্রসন্ন",
    "austere": "উগ্র, একান্ত অনাড়ম্বর; কঠোর, অলংকারহীন",
    "avaricious": "অর্থলোভী",
    "aver": "সত্য বলে ঘোষনা করা",
    "aversion": "অনীহা",
    "axiomatic": "স্বত",
    "banal": "বহুব্যবহৃত",
    "banish": "নির্বাসিত করা, বিতাড়িত করা",
    "baroque": "অলঙ্কারবহুল",
    "barrage": "বাঁধ, প্রতিবন্ধক, একটানা কাউকে প্রশ্ন করা",
    "barren": "অনুর্বর",
    "base": "ভিত্তি",
    "bawdy": "অশ্লীল, অসচ্চরিত্র",
    "befuddled": "হতবুদ্ধি করা",
    "belie": "মিথ্যা বা ভুল বর্ননা দেওয়া",
    "belligerent": "যুদ্ধভাবাপন্ন",
    "beneficent": "কল্যাণময়",
    "benevolent": "দানশীল, পরোপকারেচ্ছু",
    "benign": "বিপজ্জনক নয় এমন",
    "berate": "তীব্র ভৎষনা করা",
    "bereft": "বঞ্চিত",
    "betray": "বিশ্বাসঘাতকতা করা, গুপ্তরহস্য প্রকাশ করা",
    "blithe": "হাসিখুশি, প্রফুল্লিত,আনন্দিত",
    "bogus": "মিথ্যা",
    "boisterous": "কর্কশ ও প্রচন্ড, হৈচৈইপূর্ণ",
    "bolster": "দৃঢ় করা",
    "bombastic": "শব্দাড়ম্বরপূর্ণ, অত্যধিক জমকালো",
    "boorish": "অভদ্র",
    "bravado": "বাহাদুরি",
    "brazen": "নির্লজ্জ",
    "bridle": "লাগাম, নিয়ন্ত্রিত করা",
    "brook": "ছোট নদী, সহ্য করা",
    "bucolic": "গ্রাম্য",
    "buoyant": "প্রাণবন্ত",
    "burgeon": "দ্রুত বেড়ে ওঠা",
    "burnish": "পালিশ করা",
    "buttress": "শক্তিশালী করা",
    "byzantine": "কনস্ট্যাণ্টিনোপলের",
    "cacophonous": "কর্কশ",
    "cajole": "মিষ্টি কথায় প্রতারণা করা",
    "callow": "অনভিজ্ঞ",
    "calumny": "অপবাদ",
    "candid": "সরল, সাদাসিধে, মনখোলা, সৎ",
    "canny": "চতুর, মিতব্যয়ী",
    "canonize": "কোন (মৃত) ব্যক্তিকে মহাত্ম্য দান করা",
    "capitulate": "আত্মসমর্পণ করা",
    "capricious": "অনির্ভরযোগ্য",
    "captious": "কুতর্কপূর্ণ",
    "castigate": "শাস্তি দেত্তয়া",
    "cataclysmic": "বিপর্যয়কর",
    "cathartic": "বিশোধক পদার্থ, আবেগমুক্তিকর",
    "caustic": "ক্ষয়কারক",
    "cavalier": "অশ্বারোহী সৈনিক, শিষ্টাচার ভদ্রলোক, বীর",
    "cease": "শেষ করা, স্থগিত রাখা",
    "censure": "নিন্দা",
    "cerebral": "মস্তিষ্ক-সংক্রান্ত",
    "chagrin": "বিরক্তি, অসন্তোষ",
    "chary": "সাবধান",
    "chastise": "কঠোর শাস্তি দেওয়া",
    "chauvinistic": "উগ্র জাতীয়তাবাদী",
    "cherish": "স্নেহভবে লালন করা",
    "chicanery": "প্রতারণা",
    "chivalrous": "সাহসী",
    "churlish": "অসভ্য",
    "circumscribe": "বেষ্টন করা",
    "circumspect": "সবদিকে নজর রাখে এমন, সতর্ক",
    "clamorous": "উচ্চশব্দকারী",
    "clandestine": "গোপন",
    "clangor": "একটানা ঝনঝনে শব্দ",
    "cloak": "ছদ্মবেশ",
    "coalesce": "সমবেত হত্তয়া, একসঙ্গে জন্মান",
    "coercion": "বলপূর্বক নিয়ন্ত্রণ",
    "cogent": "জোরালো",
    "cogitate": "গভীর-ভাবে চিন্তা করা",
    "coin": "মুদ্রা, উদ্ভাবন করা",
    "collaborate": "সহযোগিতা করা",
    "collude": "গোপনে ষড়যন্ত্র করা",
    "comity": "ভদ্রতা",
    "commence": "আরম্ভ",
    "commensurate": "তুল্য, সমানুপাতিক",
    "commiserate": "সহানুভূতি প্রকাশ করা",
    "compelling": "বাধ্যকারী",
    "competent": "দক্ষ",
    "complacent": "আত্মসন্তুষ্ট",
    "complementary": "পরিপূরক",
    "comply": "আদেশ বা ইচ্ছা অনুসারে কাজ করা",
    "compromise": "মীমাংসা",
    "conciliatory": "বন্ধুত্বপূর্ণ",
    "conclusive": "চূড়ান্ত",
    "condone": "ক্ষমা বা উপেক্ষা করা",
    "conducive": "সহায়ক",
    "conflagration": "অগ্নিকাণ্ড",
    "confound": "হতবুদ্ধি করা",
    "congenial": "মনোমত, উপযুক্ত",
    "conjectural": "আনুমানিক",
    "connoisseur": "রসপণ্ডিত",
    "consensus": "ঐক্য",
    "conspicuous": "সুস্পষ্ট",
    "conspire": "চক্রান্ত",
    "construe": "ভাষান্তরিত করা",
    "contempt": "অবজ্ঞা",
    "contend": "তর্কবিতর্ক করা",
    "contentious": "কুস্বভাব, ঝগড়াটে",
    "contravene": "লঙ্ঘন করা, বিরুদ্ধে যাওয়া",
    "contretemps": "দুর্ভাগ্যজনক ঘটনা",
    "contrite": "অনুতপ্ত",
    "convalescent": "অসুখের পর শরীরে বল ফিরে পাচ্ছে এমন",
    "conventional": "প্রচলিত",
    "conviction": "দৃঢ় বিশ্বাস, অপরাধী সাব্যস্ত হওয়া",
    "convivial": "প্রফুল্ল",
    "convoluted": "জটিল",
    "copious": "প্রচুর",
    "cordial": "আন্তরিক",
    "corporeal": "দেহধারী",
    "correlate": "পরস্পর সম্পর্কযুক্ত হওয়া বা করান",
    "corroborate": "দৃঢ় করা",
    "cosmopolitan": "বিশ্বজনীন, সর্বজনীন",
    "countenance": "মুখাকৃতি, সমর্থন করা",
    "covert": "গুপ্ত",
    "covet": "লোভ করা, ব্যাকুলভাবে কামনা করা",
    "coy": "লাজুক",
    "craven": "কাপুরূষ",
    "credible": "বিশ্বাসযোগ্য",
    "crestfallen": "হতাশ",
    "croon": "গুনগুন করে গান করা",
    "cumbersome": "কষ্টকর",
    "cunning": "চতূর, ধূর্ত",
    "curb": "প্রতিবন্ধক",
    "curmudgeon": "বদমেজাজি লোক, কৃপণ লোক",
    "cursory": "দ্রুত",
    "curtail": "সংকোচন করা",
    "daunting": "ভীতিকর",
    "dawdle": "বাজে কাজে সময় নষ্ট করা, আলস্যে কাটান",
    "dearth": "অভাব",
    "debilitating": "দুর্বল করা",
    "debunk": "মিথ্যা ধারণা প্রকাশ করা",
    "decadent": "অধ",
    "decipher": "সংকেত লিপির অর্থ উদ্ধার করা",
    "decorum": "শালীনতা",
    "decry": "সমালোচনা করা",
    "deference": "শ্রদ্ধা",
    "deflect": "পরিবর্তন করা",
    "deft": "দক্ষ",
    "deify": "দেবতুল্য করা",
    "deleterious": "ক্ষতিকর",
    "deliberate": "ইচ্ছাকৃত",
    "delineate": "চিত্র অঙ্কিত করা,পুঙ্খানু পুঙ্খরূপে বর্ণনা করা",
    "delusion": "ভ্রম",
    "demur": "দ্বিধা করা",
    "denounce": "কোনো চুক্তি বা শর্তের অবসান ঘোষণা করা, সমালোচনা করা",
    "deportment": "চালচলন",
    "depose": "গদিচু্যত করা",
    "deprecate": "অনুমোদন না করা",
    "deride": "ঠাট্টা করা",
    "derivative": "ব্যুৎপন্ন",
    "desiccate": "শুকান",
    "despotic": "স্বৈর",
    "desultory": "এলোমেলো, উদ্দেশ্যহীন​",
    "detente": "বিভিন্ন রাষ্ট্রের মধ্যে বৈরিতার অবসান",
    "deviate": "পথভ্রষ্ট হত্তয়া",
    "diatribe": "সুদীর্ঘ বিতর্ক",
    "dichotomy": "বৈপরীত্য, দ্বিবিভাজন",
    "dictate": "নির্দেশ",
    "didactic": "উপদেশমূলক, শিক্ষামূলক",
    "diffident": "লজ্জাশীল",
    "diffuse": "ছড়াইয়া পড়া",
    "digression": "অপ্রাসঙ্গিক বিষয়ের আলোচনা",
    "dilatory": "দীর্ঘসূত্রি",
    "diminutive": "সংকোচিত",
    "dirge": "অস্ত্যেষ্টিক্রিয়ার সময় গাওয়া শোক সঙ্গীত",
    "discernible": "স্পষ্টভাবে প্রতীয়মান",
    "discomfit": "পরাজিত করা",
    "discount": "ছাড়",
    "discreet": "বিচক্ষণ",
    "discrepancy": "অমিল",
    "disdain": "অবজ্ঞা",
    "disentangle": "পাক খোলা, উদ্ধার করা",
    "disingenuous": "কপট",
    "disinterested": "নিরপেক্ষ",
    "disparate": "বিসদৃশ",
    "dispense": "বিতরণ করা, প্রয়োগ করা",
    "disperse": "ছড়িয়ে পড়া, ছত্রভঙ্গ করা",
    "dissemble": "ছদ্মবেশ ধারণ করা, গোপন রাখা, ভান করা",
    "disseminate": "প্রচার করা",
    "dissent": "ভিন্নমত পোষণ করা",
    "dissident": "ভিন্নমতাবলন্বী",
    "distend": "ফাঁপা",
    "distill": "পাতন করা",
    "distort": "বিকৃত করা",
    "distressed": "দূর্দশাগ্রস্থ​",
    "divergent": "বিপথগামী",
    "divorced": "তালাকপ্রাপ্ত",
    "divulge": "ফাঁস করা",
    "doctrinaire": "তাত্ত্বিক",
    "documentary": "তথ্যচিত্র",
    "dogged": "জিদি",
    "dogmatic": "অন্ধবিশ্বাসী",
    "dowdy": "রুচিহীন",
    "droll": "হাস্যরসিক",
    "dubious": "সন্দেহজনক",
    "dupe": "প্রতারিত ব্যক্তি",
    "duplicitous": "প্রতারণাপূর্ণ",
    "duress": "কয়েদ",
    "dwindling": "হ্রাস পাত্তয়া, মৃতপ্রায়",
    "ebullient": "উচ্ছ্বসিত",
    "eccentric": "অদ্ভুতস্বভাব",
    "echelon": "পর্যায়",
    "eclectic": "সমস্ত কিছুর ভাল বাছিয়া গ্রহন করে এমন",
    "eclipse": "অন্ধকার",
    "economy": "অর্থনীতি",
    "edify": "নৈতিক উন্নতিসাধন করা",
    "efficacious": "ফলপ্রদ",
    "egregious": "গুরুতর",
    "elated": "গর্বিত",
    "elementary": "প্রাথমিক",
    "elicit": "প্রকাশ করা",
    "elitist": "অভিজাত",
    "eloquent": "বাক্পটু",
    "elucidate": "স্পষ্ট করা, ব্যাখ্যা করা",
    "embellish": "অলঙ্কৃত করা",
    "empirical": "গবেষণামূলক",
    "emulate": "অনুকরণ করা",
    "enchant": "মুগ্ধ করা",
    "encyclopedic": "বিস্তৃত তথ্যপূর্ণ",
    "endemic": "স্থানীয়",
    "enervate": "শক্তিহীন করা",
    "engender": "উত্পাদন করা, জন্ম দেওয়া",
    "enigmatic": "দুর্বোধ্য",
    "enmity": "শত্রুতা",
    "ennui": "অবসাদ",
    "enthrall": "মুগ্ধ করা",
    "entitled": "অধিকারী",
    "entrenched": "প্রোথিত, দৃঢ়ভাবে স্থাপন করা",
    "ephemeral": "ক্ষণজীবী",
    "equanimity": "মনের স্থিরতা",
    "equitable": "ন্যায়সঙ্গত, যথার্থ",
    "equivocate": "বাক্চাতুরী করা",
    "eradicate": "সমূলে উত্পাটন করা, উচ্ছেদ করা",
    "erratic": "অস্থির",
    "erudite": "বিদ্বান্",
    "escalate": "ধাপে ধাপে বৃদ্ধি করা",
    "eschew": "বর্জন করা",
    "esoteric": "আভ্যন্তরীণ,  অল্প কয়েকজন নির্বাচিত ব্যক্তিকে শেখানো হয় এমন",
    "estimable": "শ্রদ্ধেয়",
    "estranged": "বিছিন্ন",
    "euphemism": "শ্রুতিকটু পদের পরিবর্তে কোমলতর পদের প্রয়োগ",
    "euphoric": "আনন্দ-চঞ্চল অবস্থা",
    "evade": "কৌশলে এড়ান",
    "evanescent": "ক্ষণস্থায়ী",
    "evasive": "চাতুরী দ্বারা এড়িয়ে যায় এমন",
    "evoke": "আহ্বান করা",
    "exacerbate": "অধিকতর খারাপ করা",
    "exacting": "বলপূর্বক আদায়কারী",
    "exasperated": "উত্তেজিত করা",
    "excoriate": "কঠোর সমালোচনা করা",
    "exculpate": "দোষক্ষালন করা",
    "exhaustive": "সম্পূর্ণ",
    "exhilarating": "উল্লাসজনক",
    "exhort": "উত্সাহিত করা",
    "exigent": "অত্যাবশ্যক, জরুরী",
    "exonerate": "দোষ ক্ষমা করা",
    "exorbitant": "মাত্রাতিরিক্ত, অত্যধিক",
    "exorcise": "ভুত ঝাড়া",
    "exotic": "বহিরাগত",
    "expatiate": "বিস্তৃতভাবে আলোচনা করা",
    "expedient": "সুবিধাজনক বা উপযোগী",
    "expedite": "ত্বরাণ্বিত করা, দূত প্রেরণ করা",
    "explicable": "যাহা ব্যাখ্যা করা যায় এমন",
    "exploitative": "শোষণমূলক",
    "extemporize": "উপস্থিতমত রচনা করা",
    "extraneous": "বিদেশী",
    "extrapolate": "পূর্বেই দেখা",
    "extravagant": "অমিতব্যয়ী",
    "fabricate": "জাল করা, বানিয়ে বলা",
    "facetious": "কৌতুকপ্রিয়, স্ফূর্তিবাজ",
    "factious": "বিরোধপূর্ণ",
    "fallacious": "প্রতারণাপূর্ণ",
    "fallible": "ভুল করতে পারে এমন",
    "fallow": "পতিত",
    "falter": "তোতলান, আমতা-আমতা করা",
    "fanciful": "কল্পনাপূর্ণ",
    "fastidious": "খুঁতখুঁতে",
    "fawn": "পা চাটা",
    "feasible": "সম্ভবপর",
    "feckless": "অসহায়",
    "fecund": "উর্বর",
    "feeble": "দুর্বল",
    "feign": "ভান করা",
    "feint": "কৃত্রিম আক্রমণ",
    "felicitous": "যথাযোগ্য",
    "fervent": "উৎসাহজনক",
    "fervid": "উৎসাহজনক",
    "fervor": "উত্সাহ",
    "fester": "পচে যাওয়া",
    "fickle": "চঞ্চল, অস্থির, পরিবর্তনশীল",
    "figurative": "আলংকারিক",
    "finicky": "খুঁতখুঁতে",
    "flagrant": "অতি অসৎ",
    "flamboyant": "অত্যন্ত রঞ্জিত বা সুসজ্জিত",
    "fledgling": "যে পক্ষি শাবকের সবে মাত্র পালক গজাইয়াছে",
    "florid": "অলংকারপূর্ণ",
    "flout": "অবজ্ঞা করা",
    "flummoxed": "বিভ্রান্ত করা, হতবুদ্ধি করা",
    "flustered": "বিক্ষুব্ধ করা",
    "foil": "ব্যার্থ করা",
    "foment": "উসকে দেওয়া",
    "foolhardy": "মূর্খের মত সাহসী",
    "forbear": "ধৈর্যশীল হওয়া",
    "foreseeable": "সুদুর",
    "forestall": "কাউকে বিপর্যস্ত করা কিংবা পরিকল্পনা ইত্যাদি বানচাল করা",
    "forsake": "পরিত্যাগ করা",
    "fortitude": "বিপদ, যন্ত্রণা বা অসুবিধা সহ্য করা",
    "fortuitous": "আকস্মিক",
    "fractious": "বদমেজাজি, ঝগড়াটে",
    "frailty": "ভঙ্গুরতা",
    "fraught": "পরিপূর্ণ, বিপদের সম্ভাবনাপূর্ণ অভিযান",
    "fret": "জ্বালাতন করা",
    "frivolous": "অসার",
    "fruitful": "ফলপ্রসূ",
    "fulcrum": "অবলম্বন",
    "fungible": "বিনিময়যোগ্য",
    "furtive": "গোপন",
    "futile": "বৃথা",
    "gaffe": "ভুল পদক্ষেপ",
    "gainsay": "অস্বীকার করা",
    "galvanize": "উত্তেজিত করা",
    "garrulous": "বাচাল",
    "gauche": "কান্ডজ্ঞানহীন, পরিস্থিতি বা লোক বুঝে কথা বলার বা আচরণ কান্ডজ্ঞানহীন, করার ক্ষমতাবর্জিত লোকব্যবহার-অপুট",
    "gawky": "লাজুক",
    "glib": "অনর্গল কথা বলতে পারে এমন বাক্‌পটু",
    "glum": "বিষন্ন, বিষাদগ্রস্ত",
    "goad": "খোঁচানো, উত্তেজিত করা",
    "gratify": "খুশি করা, তৃপ্ত করা",
    "gratuitous": "ভিত্তিহীন",
    "grievance": "অভিযোগ",
    "grovel": "পা চাটা, নিজেকে হীন করা",
    "gullible": "অতিসরল",
    "hackneyed": "বহুলব্যবহৃত",
    "hamper": "বাধা দেওয়া",
    "haphazard": "এলোমেলো",
    "harangue": "জন সাধারনের নিকট উচ্চস্বরে বক্তৃৃতা করা",
    "harbinger": "অগ্রদূত",
    "haughty": "উদ্ধত, একগুঁয়ে",
    "headstrong": "উদ্ধত, একগুঁয়ে",
    "heady": "নেশাগ্রস্থ​",
    "heed": "মনোযোগ দেওয়া",
    "heterodox": "প্রচলিত মতের বিরোধী",
    "heterogeneous": "বিভিন্ন ধর্মী",
    "hinder": "বাধা দেওয়া",
    "histrionic": "নাটুকে",
    "hodgepodge": "জগাখিচুড়ি",
    "homogeneous": "সমজাতীয়",
    "humdrum": "একঘেয়ে",
    "hyperbole": "অতিরঞ্জন",
    "hysterical": "হিস্টিরিয়া-গ্রস্ত",
    "iconoclastic": "সংস্কারের আক্রমণকারী",
    "idiosyncratic": "স্বকীয়",
    "illusory": "মিথ্যা, ছলনাময়, প্রতারণাপূর্ণ",
    "imbroglio": "বিশৃঙ্খলা, ঝগড়াঝাঁটি, তর্কবিতর্ক",
    "imminent": "আসন্ন",
    "immure": "কারাবদ্ধ করা",
    "immutable": "অপরিবর্তনীয়",
    "impair": "দুর্বল করা",
    "impede": "বাধা দেওয়া",
    "imperious": "জাঁদরেল, জবরদস্ত",
    "impertinent": "অপ্রাসঙ্গিক",
    "imperturbable": "প্রশান্ত, স্থির, বিক্ষোভের অযোগ্য",
    "impetuous": "বেগবান, আবেগপ্রবন",
    "implacable": "সন্তুষ্ট বা শান্ত করা যায় না এমন",
    "implicit": "আভাসিত",
    "improvise": "মুহুর্তে হাতের কাছে যা পাওয়া যায় তাই দিয়ে তাৎক্ষণিকভাবে কিছু তৈরি করা বা জোগান দেওয়া, তাৎক্ষণিকভাবে উদ্ভাবন/প্রস্তুত কর",
    "impudent": "বেহায়া",
    "impugn": "সত্যতা অস্বীকার করা",
    "inborn": "সহজাত",
    "incendiary": "উত্তেজনা সৃষ্টিকারী",
    "incessant": "বিরামহীন, নিরবচ্ছিন্ন",
    "inchoate": "অপরিণত",
    "incidental": "প্রাসঙ্গিক",
    "inclined": "প্রবণ",
    "incongruous": "বেমানান",
    "incontrovertible": "সুনিশ্চিত, নিঃসংশয়",
    "incredulous": "বিশ্বাসহীন",
    "indecorous": "অশোভন",
    "indefatigable": "অবিশ্রান্ত, অধ্যবসায়ী",
    "indiscriminate": "এলোপাথাড়ি",
    "indispensable": "অত্যাবশ্যক",
    "indolent": "পরিশ্রমবিমুখ",
    "industrious": "পরিশ্রমী",
    "inform": "জানানো",
    "ingenuous": "সরল, মনখোলা, স্বাভাবিক",
    "ingrained": "বদ্ধমূল",
    "inhibit": "নিষেধ করা, বাধা দেওয়া",
    "inimical": "শলক্রভাবাপন্ন",
    "innocuous": "ক্ষতি করে না এমন",
    "inscrutable": "দুর্বোধ্য",
    "insipid": "স্বাদহীন",
    "insolent": "অশিষ্ট, অপমানকর",
    "insular": "জলবেষ্টিত",
    "interchangeable": "বিনিময় যোগ্য",
    "intermittent": "থেমে-থেমে হওয়া",
    "intertwined": "পাকানো",
    "intimate": "অন্তরঙ্গ, ঘনিষ্ঠ",
    "intransigent": "আপসহীন মনোভাব",
    "intrepid": "নিরাতঙ্ক, সাহসী",
    "intrigue": "চক্রান্ত",
    "intrinsic": "সহজাত",
    "inundate": "প্লাবিত করা, নিমজ্জিত করা",
    "invasive": "আক্রমণকর",
    "inveigle": "ছলচাতুরি বা স্তাবকতা মাধ্যমে কিছু করতে পটান",
    "inveterate": "বদ্ধমূল",
    "invidious": "অসন্তোষ",
    "invigorate": "সজীব করা",
    "inviolate": "অলঙ্ঘিত",
    "irascible": "বদমেজাজী",
    "ire": "ক্রোধ",
    "irksome": "বিরক্তিকর",
    "ironclad": "লৌহবর্মভূষিত",
    "irresolute": "অস্থিরচিত্ত",
    "irreverent": "শ্রদ্ধাহীন",
    "itinerant": "ভ্রমণকারী",
    "jeopardize": "বিপন্ন",
    "jettison": "বর্জন করা",
    "jocund": "প্রফুল্লিত",
    "judicious": "সুবিচারপূর্ণ",
    "laconic": "সংক্ষিপ্ত",
    "lambaste": "আচ্ছা করে ধোলাই দেওয়া",
    "lament": "শোক করা",
    "lampoon": "কাউকে আক্রমণ বা উপহাস করে রচিত তীব্র ব্যঙ্গাত্মক রচনা",
    "languid": "দুর্বল",
    "languish": "শক্তিহীনতা",
    "largesse": "ঔদার্য",
    "laudable": "প্রশংসনীয়",
    "lavish": "প্রচুর ব্যয় করা",
    "lax": "শিথিল",
    "lethargic": "অলস",
    "liability": "দায়",
    "libertine": "চরিত্রহীনা",
    "limpid": "পরিষ্কার",
    "lionize": "খ্যাতনামা বা গণ্যমান্য ব্যক্তিরূপে প্রতিষ্ঠিত করা",
    "loathe": "ঘৃণা করা",
    "loquacious": "বাক্পটু",
    "lucid": "স্বচ্ছ",
    "lucrative": "লাভজনক",
    "lugubrious": "নিরানন্দ",
    "lull": "ঘুম পাড়ান",
    "macabre": "ভয়াবহ",
    "magisterial": "গর্বিত",
    "magnanimous": "মহানুভব",
    "malfeasance": "অবৈধ কাজ",
    "malign": "অপকারী",
    "malleable": "নমনীয়",
    "manacle": "হাতকড়ি",
    "manifest": "স্পষ্ট প্রকাশ করা",
    "marginalize": "প্রান্তীয়",
    "mawkish": "বিরক্তিকর ভাবপ্রবণ",
    "mendacity": "অসত্যতা",
    "mercenary": "অর্থ বা পুরস্কারের বিনিময়ে কাজ করে এমন",
    "mercurial": "পরিবর্তনশীল",
    "meritorious": "প্রশংসনীয়, গুণসম্পন্ন",
    "metaphorical": "রুপকশোভিত",
    "meticulous": "অতিরিক্ত যত্নবান",
    "mettlesome": "সাহসী",
    "mimic": "অনুকরণমূলক",
    "minute": "পুঙ্খানুপুঙ্খ",
    "misanthropic": "মনুষ্যদ্বেষী",
    "miscreant": "পাজী",
    "miserly": "কিপটা",
    "misnomer": "অপ্রকৃত নাম",
    "mitigate": "উপশম করা",
    "modest": "বিনয়ী",
    "modish": "ফ্যাশান দুরস্ত",
    "mollify": "প্রশমিত করা",
    "momentary": "ক্ষণস্থায়ী",
    "monotonous": "একঘেয়ে",
    "mordant": "জ্বালাময়, মর্মভেদী",
    "morose": "বিষাদগ্রস্ত",
    "mundane": "জাগতিক, নিরানন্দ​",
    "munificent": "উদার",
    "mutiny": "কর্তৃপক্ষের বিরুদ্ধ প্রকাশ্য বিদ্রোহ",
    "myopic": "ক্ষীণদৃষ্টি",
    "nadir": "সর্বনিম্ন",
    "naive": "সাদাসিধা",
    "nascent": "জন্মলাভ করিতেছে এমন",
    "negligent": "অবহেলাকারী",
    "neophyte": "নবদীক্ষিত ব্যক্তি",
    "nettlesome": "বিরক্ত করা",
    "neutralize": "প্রতিরোধ করা",
    "nimble": "দ্রুতগামী",
    "noble": "উন্নতচরিত্র",
    "nominal": "নামমাত্র",
    "nonchalant": "উদাসীন",
    "nonplussed": "কিংকর্তব্যবিমূঢ়",
    "noxious": "অস্বাস্থ্যকর",
    "nullify": "বাতিল করা",
    "numinous": "ঐশ্বরিক",
    "obdurate": "দুর্দম",
    "obeisance": "সম্মান, শ্রদ্ধা, সালাম",
    "oblivious": "অমনোযোগী",
    "obscure": "অস্পষ্ট",
    "obsequious": "চাটুকার, ক্রীতদাসতুল্য",
    "obsolete": "অপ্রচলিত",
    "obstinate": "একগুঁয়ে",
    "obstreperous": "গোলমালপূর্ণ, হৈচৈ-করা, দুরন্ত",
    "obviate": "কৌশলে অপসারিত করা",
    "odious": "ঘৃণ্য, জঘন্য",
    "officious": "অনধিকার চর্চায় অতিতত্পর, সাহায্য করতে আগ্রহী",
    "ominous": "অশুভ",
    "omnipresent": "সর্বত্র বিরাজমান",
    "onerous": "কষ্টদায়ক",
    "opaque": "অস্বচ্ছ",
    "opprobrium": "নিন্দা, অপমান",
    "ostentatious": "জাঁকাল",
    "oust": "চাকরি থেকে বহিষ্কার করা",
    "outlandish": "অদ্ভুত",
    "outstrip": "বেরিয়ে যাত্তয়া",
    "overt": "প্রকাশ্য",
    "painstaking": "যত্নশীল",
    "palpable": "স্পর্শগ্রাহ্য",
    "panacea": "সর্বরোগহর ঔষধ",
    "panache": "ব​ড়াই ভাব",
    "paradigmatic": "দৃষ্টান্তমূলক, উদাহরণ স্বরুপ",
    "paradoxical": "প্রচলিত মতবিরোধ",
    "parochial": "সংকীর্ণ",
    "parsimonious": "অতিশয় মিতব্যয়ী",
    "partial": "আংশিক, পক্ষপাতী",
    "patent": "আবিষ্কার বা আবিষ্কৃত বস্তু নকল থেকে আইনবলে সংরক্ষণ",
    "peccadillo": "সামান্য অপরাধ",
    "peculiar": "অদ্ভুত",
    "pedantic": "বিচারবুদ্ধিহীন পণ্ডিতসুলভ",
    "pedestrian": "পথচারী",
    "pellucid": "স্বচছ",
    "penchant": "ঝোঁক",
    "pensive": "চিন্তাশীল",
    "perennial": "বহুবর্ষজীবী",
    "perfidy": "বিশ্বাসভঙ্গ",
    "perfunctory": "উদাসীনভাবে বা অনিচছার সঙ্গে কৃত",
    "perilous": "বিপজ্জনক",
    "peripheral": "সীমান্তবর্তী",
    "pernicious": "ক্ষতিকর",
    "perpetrate": "রূচিবিরূদ্ধ কিছু করা",
    "perpetuate": "চিরস্থায়ী করা",
    "perseverance": "অধ্যবসায়",
    "pertinacious": "নাছোড়বান্দা",
    "pertinent": "প্রাসঙ্গিক",
    "pervasive": "অনুপ্রেবশ প্রবণ",
    "petulant": "খিটখিটে",
    "philistine": "সঙ্কীর্ণমনা ব্যক্তি",
    "phlegmatic": "জড়",
    "pious": "ধার্মিক, সাধু",
    "pithy": "বলিষ্ঠ",
    "placate": "শান্ত করা",
    "placid": "শান্ত",
    "plaintive": "দু",
    "plastic": "প্লাস্টিক",
    "platitude": "মামুলি কথা",
    "pliant": "নমনীয়",
    "plodding": "শ্রমশীল",
    "ploy": "কর্ম-পরিকল্পনা",
    "plucky": "সাহসী",
    "poignant": "মর্মভেদী, কাঁটার মত বেঁধে বা খোঁচা দেয় এমন",
    "poise": "ভার চাপান, ভারসাম্য রক্ষা করা",
    "polarize": "সমবর্তিত করা",
    "polemical": "বিতর্কমূলক",
    "polymath": "বহুবিদ্যাজ্ঞ",
    "pomposity": "নিদারুণ আত্মম্ভরিতা",
    "portend": "ভবিষ্যদ্বাণী করা",
    "precarious": "নিরাপত্তাহীন",
    "precipitate": "দ্রুত প্রস্থান করান",
    "precipitous": "খাড়াভাবে",
    "preclude": "প্রতিরোধ করা",
    "precocious": "ইঁচড়ে পাকা",
    "predicament": "অপ্রতিকর অবস্থা",
    "predilection": "পক্ষপাত",
    "premeditate": "পূর্বাহ্নেই চিন্তা করা",
    "prescient": "দূরদর্শী",
    "presumptuous": "বেয়াদব",
    "pretentious": "ভণ্ড, ভানপূর্ণ",
    "prevaricate": "কৌশল সত্যকে এড়াইয়া যাওয়া",
    "prime": "প্রধান",
    "pristine": "আদিম",
    "probity": "সাধুতা",
    "proclivity": "স্বাভাবিক প্রবণতা",
    "prodigal": "অমিতব্যয়ী",
    "prodigious": "বিস্ময়কর",
    "proficient": "দক্ষ",
    "profligate": "অসচ্চরিত্র বা লম্পট",
    "profound": "গভীর",
    "profundity": "অসামান্যতা",
    "profuse": "প্রচুর",
    "proliferate": "প্রচুর সংখ্যায় স্বীয় বংশবৃদ্ধি",
    "prolix": "বিরক্তিকর, দৈর্ঘ্যর জন্য ক্লান্তিকর, দীর্ঘ ও শব্দবহুল",
    "propagate": "বংশ বিস্তার করা",
    "propensity": "প্রবণতা",
    "prophetic": "ভবিষ্যদ্বাণীপূর্ণ",
    "propitious": "শুভলক্ষণযুক্ত",
    "propriety": "যথাযথতা",
    "prosaic": "বেরসিক",
    "providential": "দৈব",
    "provincial": "প্রাদেশিক",
    "provocative": "উত্তেজক",
    "prowess": "বীরত্ব",
    "proxy": "অন্যের পরবর্তিরূপে কাজ করা",
    "prudent": "বিচক্ষণ",
    "prurient": "কামুক",
    "puerile": "শিশু সুলভ",
    "pugnacious": "ঝগড়াটে",
    "punctilious": "শিষ্টচারসম্পন্ন",
    "qualm": "সংশয়",
    "quandary": "কিংকর্তব্যবিমূঢ়",
    "quarantine": "যে সময় পর্যন্ত রোগ সংক্রামণ আশঙ্কায় পৃথক রাখা হয়",
    "quash": "বাতিল করা",
    "quibble": "আসল কথাটি এড়াবার জন্য কথার মারপ্যাঁচ",
    "quiescent": "স্থির, শান্ত",
    "quirky": "উদ্ভট",
    "quixotic": "ভাববিলাসী",
    "radical": "আমূল রাজনৈতিক পরিবর্তনের পক্ষপাতী",
    "ramification": "প্রভাব",
    "rapacious": "অর্থলোভী, লুণ্ঠনকারী",
    "rational": "যুক্তিসংগত",
    "ravage": "ধ্বংস বা নষ্ট করা",
    "recant": "ভুল স্বীকার করিয়া প্রত্যাহার করা",
    "reconcile": "মিলনসাধন করা",
    "recondite": "দুর্বোধ্য",
    "recourse": "সাহায্যের চেষ্টা, আশ্রয়",
    "recrudescent": "পুনঃপ্রকোপ, পুনরায় প্রাদুর্ভাব",
    "redoubtable": "ভয়ংকর",
    "refine": "শোধন করা",
    "refute": "মিথ্যা বা ভুল প্রমাণ করা",
    "regress": "প্রত্যাবর্তন",
    "reiterate": "পুনরাবৃত্তি করা",
    "relegate": "নিম্নপদে সরানো",
    "relent": "কোমল বা নরম হওয়া",
    "relinquish": "পরিত্যাগ করা",
    "relish": "সুস্বাদ",
    "remedial": "আরোগ্যকর",
    "remuneration": "পারিশ্রমিক",
    "render": "পারিশ্রমিক, প্রতিদান দেত্তয়া",
    "renege": "পরিত্যাগ করা",
    "renounce": "পরিত্যাগ করা",
    "repercussion": "প্রতিক্রিয়া",
    "repertoire": "থিয়েটারে ঐভাবে নাটক মঞ্চস্থ",
    "replenish": "পূরণ করা",
    "reproach": "ভর্ত্সনা",
    "repudiate": "অস্বীকার করা",
    "repugnant": "বেমানান",
    "resilient": "স্থিতিস্থাপক",
    "resolute": "অটল",
    "restive": "অশান্ত",
    "reticent": "স্বল্পভাষী",
    "retiring": "অবসরের",
    "rhetoric": "অলঙ্কারশাস্ত্র",
    "rigor": "কঠোর",
    "robust": "বলবান, স্বাস্থ্যবান, শক্তসমর্থ",
    "rudimentary": "প্রাথমিক",
    "ruminate": "গভীর চিন্তা, জাবর কাটা",
    "sadistic": "ধর্ষকামী",
    "sagacious": "প্রজ্ঞ",
    "salubrious": "স্বাস্থ্যকর",
    "salutary": "স্বাস্থ্যকর, উপকারী",
    "sanctimonious": "বক-ধামির্ক, ভণ্ডামিপূর্ণ",
    "sanction": "অনুমোদন",
    "sanguine": "আশাবাদী",
    "satirical": "বিদ্রুপাত্মক",
    "scant": "যথেষ্ট নয় এমন",
    "scathing": "কঠোর",
    "schism": "বিভেদ",
    "scintillating": "চকচকে, স্ফুলিঙ্গ ছড়ান",
    "scorn": "অবজ্ঞা",
    "scrupulous": "নৈতিক বিবেকসম্পন্ন",
    "sedulous": "পরিশ্রমী",
    "sensational": "উত্তেজনাপূর্ণ",
    "sentimental": "ভাবপ্রবণ",
    "serene": "শান্ত",
    "sever": "ছিন্ন করা",
    "sham": "নকল",
    "shrill": "উচ্চ ও তীক্ষ",
    "skirt": "কিনারা",
    "skittish": "ভীতু",
    "skullduggery": "অত্যন্ত পটু বা সেয়ানা লোক",
    "slander": "অপবাদ",
    "slight": "অসম্মান",
    "slovenly": "অগোছাল",
    "sluggish": "কুঁড়ে, জড়প্রকৃতি, মন্তরগতি",
    "soliloquy": "(নাটকে)স্বগতোক্তি",
    "somnolent": "নিদ্রালু",
    "sophisticated": "বাস্তববুদ্ধিসম্পন্ন",
    "sophistry": "কূটতর্ক",
    "soporific": "ঘুমপাড়ানি",
    "sound": "শব্দ",
    "sparse": "বিরল",
    "spartan": "কন্টকসহিষ্ণু; নির্ভীক",
    "specious": "সংগত বা সত্য বলিয়া প্রতীয়মান কিন্তু প্রকৃতপক্ষে তাহা নহে",
    "spendthrift": "অপব্যয়ী ব্যক্তি",
    "sporadic": "বিক্ষিপ্ত",
    "spurious": "মিথ্যা",
    "spurn": "লাথি মারা",
    "squander": "অপব্যয় করা",
    "stalwart": "শক্ত সমর্থ, দীর্ঘকায় ও বলবান, সাহসী ও স্থিরসংকল্প",
    "steadfast": "অটল",
    "stern": "কঠোর, অদম্য, অদমনীয়",
    "stigmatize": "কলঙ্কপূর্ণ করা",
    "stinting": "কৃপণতা করা",
    "stoic": "সুখ-দুঃখ উদাসীন ব্যক্তি",
    "stolid": "অবিচলিত, প্রাণশক্তিহীন",
    "strife": "শত্রুতা",
    "stringent": "কঠোর, বাধ্যতামূলক",
    "subjective": "বিষয়ী",
    "subordinate": "পদমর্যাদায় নিচু এমন লোক, অধীনস্ত",
    "subservient": "অধীন",
    "subside": "থিতান",
    "substantiate": "প্রতিপন্ন করা",
    "subsume": "অন্তর্ভূত করা",
    "subtle": "সূক্ষ্ম",
    "subvert": "পরাভূত করা, ধ্বংস করা",
    "superficial": "অগভীর",
    "superfluous": "অতিরিক্ত",
    "supersede": "অপরের পরিবর্তে স্থান অধিকার করা",
    "supplant": "স্থানচু্যত করা",
    "supple": "নমনীয়",
    "supplicate": "অনুনয়-বিনয় করা",
    "surmount": "শীর্ষদেশে থাকা",
    "surreptitious": "গুপ্ত",
    "suspect": "সন্দেহভাজন",
    "swindle": "প্রতারণ",
    "synoptic": "সারসংক্ষেপ",
    "tacit": "নীরব",
    "taciturn": "অল্পভাষী",
    "tact": "কৌশলের সূক্ষ্মতা",
    "tangential": "স্পর্শিনী",
    "tangible": "বাস্তব",
    "tantalizing": "বিশ্বাস জাগাইয়া প্রতারণা করা",
    "tantamount": "সমপরিমাণ",
    "tarnish": "কলঙ্কিত করা",
    "tedious": "ক্লান্তিকর",
    "temerity": "হঠকারিতা",
    "temper": "মেজাজ",
    "tempestuous": "প্রচণ্ড",
    "temporal": "সময়গত",
    "tenable": "রক্ষা করা যায় এমন",
    "tendentious": "উদ্দেশ্যমূলক",
    "tentative": "সম্ভাব্য",
    "tenuous": "কৃশ",
    "tepid": "কুসুম কুসুম গরম",
    "terse": "সংক্ষিপ্ত ও জোরালো",
    "thorough": "পুঙ্খানুপুঙ্খ",
    "timorous": "ভীরু",
    "tirade": "সুদীর্ঘ বক্তৃতা",
    "torpor": "অসাড়তা, নিষ্কিয়তা",
    "tortuous": "অসরল, কপট",
    "tout": "দালাল",
    "tractable": "বাধ্য",
    "tranquil": "শান্ত",
    "transcend": "অতিক্রম করিয়া যাত্তয়া",
    "transgression": "পাপ",
    "transient": "অস্থায়ী",
    "transitory": "ক্ষণস্থায়ী",
    "treatise": "গ্রন্থ",
    "trenchant": "মর্মভেদী",
    "trifling": "তুচ্ছ",
    "trivial": "নগণ্য",
    "truculent": "নিষ্ঠুর",
    "turbulent": "প্রচন্ড আলোড়নপূর্ণ",
    "turpitude": "অসচ্চরিত্রতা",
    "ubiquitous": "সর্বব্যাপী",
    "umbrage": "অবজ্ঞা করা, অপমানবোধ",
    "unalloyed": "খাঁটী",
    "undercut": "জিনিসপত্র অন্য বিক্রেতার দামের থেকে কম দামে বিকোনো",
    "undermine": "গোপনে বিরুদ্ধাচরণ করা",
    "underscore": "জোর দেওয়া",
    "understated": "আসলে যা তার চেয়ে কমিয়ে বলা বা দেখানো, অস্পষ্ট",
    "universal": "সার্বজনীন",
    "unprecedented": "অভূতপূর্ব",
    "unscrupulous": "বিবেকবর্জিত",
    "unseemly": "অনুচিত",
    "upbraid": "ভর্ত্সনা করা",
    "urbane": "সভ্য",
    "utilitarian": "উপযোগবাদী",
    "utterly": "সম্পূর্ণূরূপে",
    "vacillate": "দ্বিধাগ্রস্ত হত্তয়া, দোলায়মান হওয়া",
    "valor": "বীরত্ব",
    "vanquish": "(যুদ্ধ) পরাজিত করা",
    "vapid": "স্বাদহীন",
    "venal": "অর্থের বিনিময়ে অন্যায় ভাবে কাজ করতে ইচ্ছুক",
    "venerate": "শ্রদ্ধা করা",
    "veracity": "সত্যবাদিতা",
    "verbose": "বাগাড়ম্বরপূর্ণ",
    "verisimilitude": "সত্য বলিয়া প্রতীয়মানতা",
    "veritable": "সত্য",
    "versatile": "বহু বিষয়ে পন্ডিত",
    "verve": "উদ্দীপনা",
    "vexation": "জালাতন",
    "viable": "টেকসই", "বাস্তবায়নযোগ্য",
    "vigilant": "সতর্ক",
    "virulent": "অত্যন্ত বিষাক্ত",
    "visionary": "স্বপ্নদর্শী",
    "vitality": "জীবনীশক্তি",
    "vitiate": "অপবিত্র করা",
    "vivacious": "প্রাণবন্ত",
    "vociferous": "কোলাহলপূর্ণ; গলাবাজি করে এমন",
    "volatile": "উদ্বায়ী, পরিবর্তনশীল",
    "wane": "ক্ষীণ হওয়া",
    "wary": "সতর্ক",
    "wayward": "একগুয়ে",
    "weary": "ক্লান্ত",
    "wheedle": "প্রতারিত করা",
    "whimsical": "অদ্ভুত কল্পনাপূর্ণ",
    "wily": "কূটবুদ্ধি",
    "woeful": "দু:খপূর্ণ, শোচনীয়",
    "xenophobic": "বিদেশী লোক বা বিদেশী কোনো কিছু সম্বন্ধে ভয়",
    "yield": "উৎপাদন করা,  আত্মসমর্পণ করা",
    "zealous": "প্রবল উদ্দীপনাপূর্ণ",
    "zenith": "সর্বোচ্চ স্থান",
}
